version: 2.1
jobs:
  test:
    docker:
      - image: maven:3.6-jdk-12
    steps:
      - checkout
      - run:
          name: Build and Unit tests
          command: mvn clean verify
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login at hub docker
          command: 'docker login -u $DOCKER_USER -p $DOCKER_PASS'
      - run: 'docker build . -t jytakano/apresentacao-circle-ci:latest'
      - run:
          name: Push to hub docker
          command: 'docker push jytakano/apresentacao-circle-ci:latest'
workflows:
  version: 2
  default_workflow:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master